FROM python:3.11-bullseye
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG USERNAME=devops
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

COPY ./api/requirements.txt .

RUN apt update && apt upgrade -y && \
    pip install --upgrade pip && \
    pip install -r requirements.txt --upgrade

# Run as user
USER $USERNAME
